spring.application.name=backend
server.port=8081

watsonx.api-key=${WATSONX_API_KEY:}
watsonx.project-id=${WATSONX_PROJECT_ID:}
watsonx.url=${WATSONX_URL:}
watsonx.model-id=ibm/granite-4-h-small

tago.service-key=${TAGO_SERVICE_KEY:}
tago.base-url=http://apis.data.go.kr/1613000/ExpBusInfo